channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cachecontrol=0.12.11
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=0.8.3
  - ffmpeg=4.2.2
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - h5py=3.7.0
  - hdf5=1.10.6
  - hdmedians=0.14.2
  - idna=3.4
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libidn2=2.3.2
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lockfile=0.12.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - natsort=7.1.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pluggy=1.0.0
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.10.11
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - readline=8.2
  - requests=2.29.0
  - scikit-bio=0.5.8
  - scipy=1.10.1
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - fonttools==4.39.3
    - mpmath==1.2.1
