name: Deploy release
on:
  push:
    tags:  # run only on new tags that follow semver MAJOR.MINOR.PATCH
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-release:
    name: Deploy release from tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build wheel
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Upload wheel and source distributions to PyPI
        run: |
          python -m pip install twine
          ls -1 dist
          python -m twine upload --u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }} --skip-existing dist/*

      - name: Publish wheel and source distributions as a GitHub release
        run: |
          python -m pip install "githubrelease>=1.5.9"
          githubrelease --github-token ${{ secrets.GH_TOKEN }} release exabiome/gtnet \
            create ${{ github.ref_name }} --name ${{ github.ref_name }} \
            --publish dist/*
